Vagrant.configure("2") do |config|
    config.vm.provider "hyperv"
    #config.vm.box = "bento/centos-7"
    config.vm.hostname = "centos-7-1"
    config.vm.network "public_network", bridge: "Rob-HyperV-InternalNetwork"
    #config.vm.provision "shell", path: "../OS/centos-7/script.sh"
    config.vm.provision "puppet" do |puppet|
      #puppet.manifests_path = "../OS/centos-7/my_manifests"
      puppet.manifest_file = "default.pp"
    end
    #config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.provider "hyperv" do |h|
      h.vmname = "centos-7-1"
      h.cpus = 2
      h.memory = 2048
      h.enable_virtualization_extensions = true
      h.linked_clone = true
    end
  end