# variables
DISTRO = "centos-7"
BOX = "bento/centos-7" # bento/centos-7, generic/ubuntu1604, generic/ubuntu1804, generic/debian8, bento/ubuntu-20.04
HOSTNAME = "centos-7-1"

Vagrant.configure("2") do |config|
  config.vm.define :lv do |lv|
    lv.vm.box = BOX
    lv.vm.provider "hyperv" 
    lv.vm.hostname = HOSTNAME 
    lv.vm.provision "shell", path: "../OS/" + DISTRO + "/script.sh" 
    lv.vm.synced_folder ".", "/vagrant", disabled: true
    lv.vm.provider "hyperv" do |lv|
      lv.vmname = HOSTNAME
      lv.maxmemory = 2048
      lv.cpus = 2
      lv.enable_virtualization_extensions = true
      lv.linked_clone = true  
    end
  end
end 
