Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.name = "centos-7-1"
    v.linked_clone = true
    v.memory = 2048
    v.cpus = 2
  end
  config.vm.box = "centos/7"
  config.vm.hostname = "centos-7-1"
  config.vm.network "private_network", type: "dhcp"
  config.vm.provision "shell", path: "../script.sh"
  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = "../my_manifests"
    puppet.manifest_file = "default.pp"
  end
end
