Vagrant.configure("2") do |config|
  #config.vm.box = "bento/centos-5.11"
  #config.vm.box = "bento/centos-6"
  #config.vm.box = "bento/centos-7"
  #config.vm.box = "parallels/ubuntu-14.04"
  #config.vm.box = "bento/ubuntu-16.04"
  #config.vm.box = "generic/ubuntu1804"
  #config.vm.box = "bento/debian-9"
  config.vm.hostname = "centos-7-1"
  #config.vm.provision "shell", path: "../OS/centos-5/script.sh"
  #config.vm.provision "shell", path: "../OS/centos-6/script.sh"
  #config.vm.provision "shell", path: "../OS/centos-7/script.sh"
  #config.vm.provision "shell", path: "../OS/ubuntu-14/script.sh"
  #config.vm.provision "shell", path: "../OS/ubuntu-16/script.sh"
  #config.vm.provision "shell", path: "../OS/ubuntu-18/script.sh"
  #config.vm.provision "shell", path: "../OS/debian-9/script.sh"
  config.vm.provision "puppet" do |puppet|
    #puppet.manifests_path = "../OS/centos-5/my_manifests"
    #puppet.manifests_path = "../OS/centos-6/my_manifests"
    #puppet.manifests_path = "../OS/centos-7/my_manifests"
    #puppet.manifests_path = "../OS/ubuntu-14/my_manifests"
    #puppet.manifests_path = "../OS/ubuntu-16/my_manifests"
    #puppet.manifests_path = "../OS/ubuntu-18/my_manifests"
    #puppet.manifests_path = "../OS/debian-9/my_manifests"
    puppet.manifest_file = "default.pp"
  end
  config.vm.provider "parallels" do |prl|
    prl.name = "centos-7-1"
    prl.memory = 2048
    prl.cpus = 2
    # add disk
    #prl.customize ["set", :id, "--device-add", "hdd", "--type", "expand", "--size", "1024"]
    # add network adaptor
    prl.customize ["set", :id, "--device-add", "net", "--type", "bridged"]
  end
end
