# variables
DISTRO = "centos-8"
BOX = "generic/centos8" # bento/centos-5.11, bento/centos-6, bento/centos-7, generic/centos8, parallels/ubuntu-14.04, bento/ubuntu-16.04, generic/ubuntu1804, bento/debian-9
HOSTNAME = "centos-8-1"

Vagrant.configure("2") do |config|
  config.vm.box = BOX
  config.vm.hostname = HOSTNAME
  config.vm.provision "shell", path: "../OS/" + DISTRO + "/script.sh" 
  config.vm.provider "parallels" do |prl|
    prl.name = HOSTNAME
    prl.memory = 2048
    prl.cpus = 2
    # add disk
    #prl.customize ["set", :id, "--device-add", "hdd", "--type", "expand", "--size", "1024"]
    # add network adaptor
    prl.customize ["set", :id, "--device-add", "net", "--type", "bridged"]
  end
end
