# variables
DISTRO = "centos-7"
BOX = "centos/7" # bento/centos-7, generic/ubuntu1604
HOSTNAME = "centos-7-1"

Vagrant.configure("2") do |config|
  config.vm.define :lv do |lv|
    lv.vm.box = BOX 
    lv.vm.hostname = HOSTNAME
    lv.vm.network :public_network,
      :dev => "br0",
      :mode => "bridge",
      :type => "bridge"
    lv.vm.provision "shell", path: "../OS/" + DISTRO + "/script.sh" 
    lv.vm.provision "puppet" do |puppet|
      puppet.manifests_path = "../OS/" + DISTRO + "/my_manifests"
      puppet.manifest_file = "default.pp"
    end
    lv.vm.provider "libvirt" do |lv|
      lv.memory = 2048
      lv.cpus = 2
    end
  end
end 
