Vagrant.configure("2") do |config|
  config.vm.define :lv do |lv|
    #lv.vm.box = "centos/7" 
    #lv.vm.box = "generic/ubuntu1604"   
    lv.vm.hostname = "centos-pc-7-1" 
    lv.vm.network :public_network,
      :dev => "br0",
      :mode => "bridge",
      :type => "bridge"
    #lv.vm.provision "shell", path: "../OS/centos-7/script.sh"
    #lv.vm.provision "shell", path: "../OS/ubuntu-16/script.sh"
    lv.vm.provision "puppet" do |puppet|
      #puppet.manifests_path = "../OS/centos-7/my_manifests"
      #puppet.manifests_path = "../OS/ubuntu-16/my_manifests"
      puppet.manifest_file = "default.pp"
    end
    lv.vm.provider "libvirt" do |lv|
      lv.memory = 2048
      lv.cpus = 2
    end
  end
end 
