Vagrant.configure("2") do |config|
    # change :lv to VM of your choice. Use _ not -
    config.vm.define :lv do |lv|
      lv.vm.box = "generic/ubuntu1604"  
      lv.vm.hostname = "ubuntu-pc-16-1" 
      lv.vm.network :public_network,
        :dev => "br0",
        :mode => "bridge",
        :type => "bridge"
      lv.vm.provision "shell", path: "../script.sh"
      lv.vm.provision "puppet" do |puppet|
        puppet.manifests_path = "../my_manifests"
        puppet.manifest_file = "default.pp"
      end
      lv.vm.provider "libvirt" do |lv|
        lv.memory = 2048
        lv.cpus = 2
      end
    end
  end 
