Vagrant.configure("2") do |config|
    config.vm.box = "bento/debian-9"
    config.vm.hostname = "debian-9-1"
    config.vm.provision "shell", path: "../script.sh"
    config.vm.provision "puppet" do |puppet|
      puppet.manifests_path = "../my_manifests"
      puppet.manifest_file = "default.pp"
    end
    config.vm.provider "parallels" do |prl|
      prl.name = "debian-9-1"
      prl.memory = 2048
      prl.cpus = 2
      # add disk
      #prl.customize ["set", :id, "--device-add", "hdd", "--type", "expand", "--size", "1024"]
      # add network adaptor
      prl.customize ["set", :id, "--device-add", "net", "--type", "bridged"]
    end
  end