# variables
DISTRO = "centos-7"
BOX = "bento/centos-7" # centos/7, centos/7, "ubuntu/trusty64" (14)
HOSTNAME = "centos-7-1"

Vagrant.configure("2") do |config|
    config.vm.provider "virtualbox" do |v| 
      v.name = HOSTNAME
      v.linked_clone = true
      v.memory = 2048
      v.cpus = 2
    end
    config.vm.box = BOX
    config.vm.hostname = "centos-7-1"
    config.vm.network "private_network", type: "dhcp"
    config.vm.provision "shell", path: "../OS/" + DISTRO + "/script.sh" 
    config.vm.provision "puppet" do |puppet|
      puppet.manifests_path = "../OS/" + DISTRO + "/my_manifests"
      puppet.manifest_file = "default.pp"
    end
  end
  